plugins {
    kotlin("jvm") version "2.3.10"
    application
    kotlin("plugin.serialization") version "2.3.10"
    id("org.graalvm.buildtools.native") version "0.10.2"
}

// Ensure ./gradlew -q hydrate is not interrupted by gradle execution updates (progress bars)
if (gradle.startParameter.taskNames.any { it.contains("hydrate") }) {
    gradle.startParameter.consoleOutput = org.gradle.api.logging.configuration.ConsoleOutput.Plain
}

group = "ai.coralprotocol" //{CORALIZER:BUILD_GROUP}
version = "1.0-SNAPSHOT" //{CORALIZER:BUILD_VERSION}

repositories {
    mavenCentral()
    mavenLocal()
}

// Directory where GraalVM native-image agent will dump collected configuration
val nativeImageConfigDir = layout.projectDirectory.dir("src/native-image").asFile
val ktorVersion = "3.2.3"


dependencies {
    testImplementation(kotlin("test"))
    val koogVersion = "0.8.0"
    api("ai.koog:koog-agents:$koogVersion")
    api("ai.koog:agents-mcp:$koogVersion")
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.7.3")
    // serialization
    implementation("org.jetbrains.kotlinx:kotlinx-serialization-core:1.8.1")
    implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.8.1")

    // Ktor server (for agent-adjacent tunnel proxy)
    implementation("io.ktor:ktor-server-core:${ktorVersion}")
    implementation("io.ktor:ktor-server-cio:${ktorVersion}")
     // Ktor client (for forwarding requests through tunnel)
    implementation("io.ktor:ktor-client-cio:${ktorVersion}")
    implementation("io.ktor:ktor-client-content-negotiation:${ktorVersion}")

}

application {
    // Kotlin top-level main in Main.kt compiles to *Kt suffix
    mainClass.set("ai.coralprotocol.coral.koog.fullexample.MainKt") //{CORALIZER:APPLICATION_MAIN_CLASS}
}

graalvmNative {
    toolchainDetection.set(false)
    binaries {
        named("main") {
            imageName.set("coral-koog-agent") //{CORALIZER:NATIVE_BINARY_IMAGE_NAME}
            mainClass.set("ai.coralprotocol.coral.koog.fullexample.MainKt") //{CORALIZER:NATIVE_BINARY_MAIN_CLASS}
            buildArgs.addAll(
                listOf(
                    "--no-fallback",
                    "-H:+ReportExceptionStackTraces",
                    "--initialize-at-build-time=kotlin.DeprecationLevel",
                    "--initialize-at-run-time=java.security.SecureRandom,com.sun.jndi.dns.DnsClient",
                    "--trace-class-initialization=java.security.SecureRandom",
                    "--trace-object-instantiation=com.sun.jndi.dns.DnsClient",
                    "--enable-http",
                    "--add-modules=java.net.http",
                    "--enable-url-protocols=https",
                    "--report-unsupported-elements-at-runtime",
                    "--no-fallback",
                    "--no-server",
                    "-H:+UnlockExperimentalVMOptions"
                )
            )

            /**
             * Pick up agent-generated configuration (reflection, resources, JNI, proxies, etc.)
             *
             * This was generated by:
             * 1. adding shadow jar (https://github.com/GradleUp/shadow)
             * 2. building a shadow jar via ./gradlew -q shadowJar
             * 3. running the app with agentlib:native-image-agent=config-output-dir=/src/native-image -jar build/libs/coral-koog-agent-1.0-SNAPSHOT.jar
             */
            buildArgs.add("-H:ConfigurationFileDirectories=${nativeImageConfigDir.absolutePath}")
        }
    }
}

tasks.test {
    useJUnitPlatform()
}

kotlin {
    jvmToolchain(24)
}

// Prevent issue where sometimes ./gradlew -q run would be considered UP-TO-DATE and not actually run
tasks.named<JavaExec>("run") {
    outputs.upToDateWhen { false }
}

tasks.register<HydrateTemplateTask>("hydrate") {
    group = "setup"
    description = "Hydrate this template into a concrete Coral Koog agent project."
}